<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dapper" Version="2.1.66" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="npgsql" Version="9.0.3" />
    <PackageReference Include="Npgsql.NetTopologySuite" Version="9.0.3" />
  </ItemGroup>

</Project>
