name: Docker Image CI

on:
  push:
    branches: [ "master", "develop", "test" ]
  pull_request:
    branches: [ "master", "develop", "test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v3

    - name: Start container
      run: docker-compose up -d
