name: Docker Image CI

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    branches: [ "master", "develop"]
env:
  TEST_RESULTS_DIR: "test-results"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Create results directory
        run: mkdir -p ${{ env.TEST_RESULTS_DIR }}

      - name: Run unit tests with results
        run: |
          cd Tests/Database.Tests
          dotnet test --configuration Release --no-restore --logger "trx;LogFileName=unit_tests.trx" --results-directory ${{ env.TEST_RESULTS_DIR }}

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: ${{ env.TEST_RESULTS_DIR }}/**/*.trx
  build:
    needs: tests 
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     
     - name: Set up Docker Compose
       uses: docker/setup-compose-action@v1
       
     - name: Run Docker Compose
       run: docker compose --env-file .env up -d --build
